### PR TITLE
Add another BERT pretraining/finetuning implementation

### PR DESCRIPTION
**Pull request by eric-haibin-lin**

### CODE REVIEW

**Comment by Jiakui** [comment]
already added~~~  please have a look

**Comment by eric-haibin-lin** [comment]
where? I didn't find it

**Comment by eric-haibin-lin** [comment]
I see. I didn't expand the detail section previous. Is it possible to add it to the top-4?

**Comment by Jiakui** [comment]
sure, will soon do it

**Comment by eric-haibin-lin** [comment]
Thanks

**Pull request closed without merging**
